const userTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    RECOVERY_SUCCESS: 'RECOVERY_SUCCESS',
    RESET_AUTH_FORMS: 'RESET_AUTH_FORMS',
    SET_ERRORS: 'SET_ERRORS',
    UPLOAD_DRIVER_FRONT_SUCCESS: 'UPLOAD_DRIVE_FRONT_SUCCESS',
    UPLOAD_DRIVER_BACK_SUCCESS: 'UPLOAD_DRIVE_BACK_SUCCESS',
    UPLOAD_CREDIT_FRONT_SUCCESS: 'UPLOAD_CREDIT_FRONT_SUCCESS',
    UPLOAD_CREDIT_BACK_SUCCESS: 'UPLOAD_CREDIT_BACK_SUCCESS',
    UPLOAD_INSURANCE_FRONT_SUCCESS: 'UPLOAD_INSURANCE_FRONT_SUCCESS',
    UPLOAD_INSURANCE_BACK_SUCCESS: 'UPLOAD_INSURANCE_BACK_SUCCESS',
    FETCH_CREDIT_DATA: 'FETCH_CREDIT_DATA',
    FETCH_DRIVER_DATA: 'FETCH_DRIVER_DATA',
    FETCH_INSURANCE_DATA: 'FETCH_INSURANCE_DATA',
    RESET_PHOTOS: 'RESET_PHOTOS',
    UPLOAD_CREDIT_ALL_SUCCESS: 'UPLOAD_CREDIT_ALL_SUCCESS',
    UPLOAD_DRIVER_ALL_SUCCESS: 'UPLOAD_DRIVER_ALL_SUCCESS',
    UPLOAD_INSURANCE_ALL_SUCCESS: 'UPLOAD_INSURANCE_ALL_SUCCESS',
}

export default userTypes; 